---

- name: test if selinux_state is set correctly
  ansible.builtin.assert:
    that:
      - ansible_selinux.config_mode is defined
      - ansible_selinux.config_mode is string
      - ansible_selinux.config_mode in [ "disabled", "enforcing", "permissive" ]
    quiet: yes

- name: test if selinux_policy is set correctly
  ansible.builtin.assert:
    that:
      - ansible_selinux.type is defined
      - ansible_selinux.type is string
      - ansible_selinux.type in [ "default", "minimum", "mls", "targeted" ]
    quiet: yes

- name: test if selinux_reboot is set correctly
  ansible.builtin.assert:
    that:
      - selinux_reboot is defined
      - selinux_reboot is boolean
    quiet: yes

- name: test if selinux_booleans is set correctly
  ansible.builtin.assert:
    that:
      - selinux_booleans is iterable
    quiet: yes
  when:
    - selinux_booleans is defined

- name: test if item.name in selinux_booleans is set correctly
  ansible.builtin.assert:
    that:
      - item.name is defined
      - item.name is string
    quiet: yes
  loop: "{{ selinux_booleans }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - selinux_booleans is defined

- name: test if item.state in selinux_booleans is set correctly
  ansible.builtin.assert:
    that:
      - item.state is boolean
    quiet: yes
  loop: "{{ selinux_booleans }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - selinux_booleans is defined
    - item.state is defined

- name: test if item.state in selinux_booleans is set correctly
  ansible.builtin.assert:
    that:
      - item.persistent is boolean
    quiet: yes
  loop: "{{ selinux_booleans }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - selinux_booleans is defined
    - item.persistent is defined
